"""adopt team schema

Revision ID: dd82ee2eeb86
Revises: 
Create Date: 2026-03-12 19:20:07.462369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd82ee2eeb86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('client', 'coach', 'admin'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CoachRegistrations',
    sa.Column('reg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('document_links', sa.String(length=500), nullable=True),
    sa.Column('application_status', sa.Enum('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('reg_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Coaches',
    sa.Column('coach_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.Enum('fitness', 'nutrition', 'both'), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('gym', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'approved', 'suspended', 'disabled', 'rejected'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('coach_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('Exercises',
    sa.Column('e_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_type', sa.Enum('barbell', 'dumbbell', 'machine', 'bodyweight', 'cables', 'bands', 'other'), nullable=True),
    sa.Column('muscle_group', sa.Enum('chest', 'back', 'shoulders', 'arms', 'legs', 'glutes', 'core', 'full_body'), nullable=True),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced'), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('e_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('coach_request', 'request_accepted', 'request_declined', 'new_workout', 'new_meal_plan', 'payment', 'system'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('SavedBilling',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('ClientRequests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['Coaches.coach_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('CoachAvailability',
    sa.Column('availability_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['Coaches.coach_id'], ),
    sa.PrimaryKeyConstraint('availability_id')
    )
    op.create_table('CoachManagement',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('suspend', 'reactivate', 'disable'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suspension_duration', sa.String(length=50), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['Coaches.coach_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('Subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'paused', 'expired'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_billing', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['Coaches.coach_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('Payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method_type', sa.Enum('credit_card', 'debit_card', 'paypal'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['SavedBilling.card_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['Users.user_id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['Coaches.coach_id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['Subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('transaction_id'))

    op.drop_table('payments')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_exercise_name'))

    op.drop_table('exercises')
    op.drop_table('savedbilling')
    op.drop_table('subscriptions')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_review'))

    op.drop_table('reviews')
    op.drop_table('activitylogs')
    op.drop_table('mealplanfood')
    op.drop_table('hires')
    op.drop_table('messages')
    op.drop_table('auditlog')
    op.drop_table('notifications')
    with op.batch_alter_table('oauthaccounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_provider_user'))

    op.drop_table('oauthaccounts')
    op.drop_table('fitnessgoals')
    op.drop_table('workoutcalendar')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('users')
    op.drop_table('passwordreset')
    op.drop_table('coachavailability')
    op.drop_table('coachmanagement')
    with op.batch_alter_table('dailycheckin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_daily_checkin'))

    op.drop_table('dailycheckin')
    op.drop_table('mealplans')
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))

    op.drop_table('coaches')
    with op.batch_alter_table('coachregistrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))

    op.drop_table('coachregistrations')
    op.drop_table('clientrequests')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('invoice_number'))

    op.drop_table('invoices')
    op.drop_table('workoutexercises')
    with op.batch_alter_table('messagelist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_conversation'))

    op.drop_table('messagelist')
    op.drop_table('workoutplans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutplans',
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'archived'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('workoutplans_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('workoutplans_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('messagelist',
    sa.Column('MessageList_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_message_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('messagelist_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('messagelist_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MessageList_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('messagelist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_conversation'), ['user_id', 'coach_id'], unique=True)

    op.create_table('workoutexercises',
    sa.Column('workout_exercise_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('exercise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rest_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.e_id'], name=op.f('workoutexercises_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['workoutplans.plan_id'], name=op.f('workoutexercises_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_exercise_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invoices',
    sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('invoice_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.ENUM('paid', 'unpaid', 'overdue'), server_default=sa.text("'unpaid'"), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('paid_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('invoices_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('invoice_number'), ['invoice_number'], unique=True)

    op.create_table('clientrequests',
    sa.Column('request_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'accepted', 'declined'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('responded_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], name=op.f('clientrequests_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('clientrequests_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coachregistrations',
    sa.Column('reg_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('qualifications', mysql.TEXT(), nullable=True),
    sa.Column('specialty', mysql.TEXT(), nullable=True),
    sa.Column('document_links', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('application_status', mysql.ENUM('pending', 'approved', 'rejected'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('rejection_reason', mysql.TEXT(), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], name=op.f('coachregistrations_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('coachregistrations_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reg_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('coachregistrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    op.create_table('coaches',
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('specialization', mysql.ENUM('fitness', 'nutrition', 'both'), server_default=sa.text("'fitness'"), nullable=True),
    sa.Column('certifications', mysql.TEXT(), nullable=True),
    sa.Column('experience_years', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gym', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cost', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'pending', 'approved', 'suspended', 'disabled', 'rejected'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('coaches_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    op.create_table('mealplans',
    sa.Column('meal_plan_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'archived'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('mealplans_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('mealplans_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_plan_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dailycheckin',
    sa.Column('checkin_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('checkin_date', sa.DATE(), nullable=False),
    sa.Column('mood', mysql.ENUM('great', 'good', 'okay', 'bad', 'awful'), nullable=True),
    sa.Column('energy_level', mysql.ENUM('High', 'Medium', 'Low', 'Running on Empty'), nullable=True),
    sa.Column('hours_of_sleep', mysql.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('soreness', mysql.ENUM('Very', 'Kind of', 'Barely', 'Not'), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('dailycheckin_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkin_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dailycheckin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_daily_checkin'), ['user_id', 'checkin_date'], unique=True)

    op.create_table('coachmanagement',
    sa.Column('action_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.ENUM('suspend', 'reactivate', 'disable'), nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('suspension_duration', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('action_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], name=op.f('coachmanagement_ibfk_2')),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('coachmanagement_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coachavailability',
    sa.Column('availability_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_of_week', mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('is_available', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('coachavailability_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('availability_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('passwordreset',
    sa.Column('reset_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('passwordreset_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reset_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('client', 'coach', 'admin'), server_default=sa.text("'client'"), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('last_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('weight', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('height', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('profile_photo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.ENUM('male', 'female', 'other', 'prefer_not_to_say'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('workoutcalendar',
    sa.Column('calendar_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), nullable=False),
    sa.Column('is_completed', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workoutplans.plan_id'], name=op.f('workoutcalendar_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('workoutcalendar_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fitnessgoals',
    sa.Column('goal_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('goal_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('target_value', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('target_unit', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('deadline', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('active', 'completed', 'deleted'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fitnessgoals_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oauthaccounts',
    sa.Column('oauth_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('provider_uid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('access_token', mysql.TEXT(), nullable=True),
    sa.Column('refresh_token', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('oauthaccounts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oauth_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('oauthaccounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_provider_user'), ['provider', 'provider_uid'], unique=True)

    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.ENUM('coach_request', 'request_accepted', 'request_declined', 'new_workout', 'new_meal_plan', 'payment', 'system'), server_default=sa.text("'system'"), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditlog',
    sa.Column('log_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('auditlog_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('message_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['messagelist.MessageList_id'], name=op.f('messages_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('messages_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hires',
    sa.Column('hire_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('active', 'completed', 'cancelled'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('hires_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('hires_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hire_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mealplanfood',
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('meal_plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_of_week', mysql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=False),
    sa.Column('meal_type', mysql.ENUM('breakfast', 'lunch', 'dinner', 'snack'), nullable=False),
    sa.Column('food_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('calories', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('protein', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('carbs', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('fat', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('portion_size', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['mealplans.meal_plan_id'], name=op.f('mealplanfood_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activitylogs',
    sa.Column('log_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('activity_type', mysql.ENUM('strength', 'cardio', 'steps', 'calories'), nullable=False),
    sa.Column('exercise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sets_completed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reps_completed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('weight_used', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('distance', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('duration_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cardio_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('step_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('calorie_intake', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('log_date', sa.DATE(), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.e_id'], name=op.f('activitylogs_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('activitylogs_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reviews',
    sa.Column('review_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('reviews_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('reviews_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_review'), ['user_id', 'coach_id'], unique=True)

    op.create_table('subscriptions',
    sa.Column('subscription_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plan_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('active', 'cancelled', 'paused', 'expired'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('next_billing', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('subscriptions_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('subscriptions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('savedbilling',
    sa.Column('card_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_four', mysql.CHAR(length=4), nullable=False),
    sa.Column('card_brand', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('expiry_month', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('expiry_year', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('is_default', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('savedbilling_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('exercises',
    sa.Column('e_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('equipment_type', mysql.ENUM('barbell', 'dumbbell', 'machine', 'bodyweight', 'cables', 'bands', 'other'), server_default=sa.text("'bodyweight'"), nullable=True),
    sa.Column('muscle_group', mysql.ENUM('chest', 'back', 'shoulders', 'arms', 'legs', 'glutes', 'core', 'full_body'), nullable=True),
    sa.Column('difficulty', mysql.ENUM('beginner', 'intermediate', 'advanced'), server_default=sa.text("'beginner'"), nullable=True),
    sa.Column('instructions', mysql.TEXT(), nullable=True),
    sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('exercises_ibfk_1')),
    sa.PrimaryKeyConstraint('e_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_exercise_name'), ['name'], unique=True)

    op.create_table('payments',
    sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coach_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subscription_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('card_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=10), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('payment_method_type', mysql.ENUM('credit_card', 'debit_card', 'paypal'), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'completed', 'failed', 'refunded'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('paid_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['savedbilling.card_id'], name=op.f('payments_ibfk_4'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], name=op.f('payments_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.coach_id'], name=op.f('payments_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], name=op.f('payments_ibfk_3'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('transaction_id'), ['transaction_id'], unique=True)

    op.drop_table('Payments')
    op.drop_table('Subscriptions')
    op.drop_table('CoachManagement')
    op.drop_table('CoachAvailability')
    op.drop_table('ClientRequests')
    op.drop_table('SavedBilling')
    op.drop_table('Notifications')
    op.drop_table('Exercises')
    op.drop_table('Coaches')
    op.drop_table('CoachRegistrations')
    op.drop_table('Users')
    # ### end Alembic commands ###
